### ISSUE TITLE
Error 289

### ISSUE THREAD

**Issue by woutervanranst** [martinorob/plexupdate#1]
i get an error 289 - google doesn't yield much
if i put the Trust Level from "Synology and trusted 3rd parties" to "anyone", it does work
is there a way to script this in? i'd like to keep that

Output
```
New Ver: 1.18.1.1973-0f4abfbcc
Cur Ver: 1.18.0.1913-e5cc93306
New Vers Available
--2019-10-27 14:26:17--  https://downloads.plex.tv/plex-media-server-new/1.18.1.1973-0f4abfbcc/synology/PlexMediaServer-1.18.1.1973-0f4abfbcc-x86_64.spk
Resolving downloads.plex.tv... 104.18.156.41, 104.18.157.41, 2606:4700::6812:9c29, ...
Connecting to downloads.plex.tv|104.18.156.41|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 124938240 (119M) [binary/octet-stream]
Saving to: '/volume1/tmp/plex/PlexMediaServer-1.18.1.1973-0f4abfbcc-x86_64.spk'

PlexMediaServer-1.18.1.1973-0f4abfbcc-x86_64.spk   100%[================================================================================================================>] 119.15M  10.1MB/s    in 11s     

2019-10-27 14:26:28 (10.8 MB/s) - '/volume1/tmp/plex/PlexMediaServer-1.18.1.1973-0f4abfbcc-x86_64.spk' saved [124938240/124938240]

Failed to install package /volume1/tmp/plex/PlexMediaServer-1.18.1.1973-0f4abfbcc-x86_64.spk, error = [289]
package Plex Media Server start successfully
```

**Comment by mcd92** [comment]
As pointed by BuffaloBuffaloBufalo in reddit (https://www.reddit.com/r/synology/comments/9wwkrz/has_anyone_successfully_installed_plexupdate_on/), the solution is to simply change the settings on Package Manager to allow the installation of packages published by "Any publisher".

@martinorob You should add this observation to the readme file.

**Comment by N1co93** [comment]
Just for your Information. You can also add the Plex certificate to the Synology Package Center. So you don't have to trust "Any publisher" 

See this plex guide. https://support.plex.tv/articles/205165858-how-to-add-plex-s-package-signing-public-key-to-synology-nas-package-center
